### ISSUE TITLE
Add support for custom interaction types

### ISSUE THREAD

**Issue by JakubTesarek** [lmc-eu/matej-client-php#107]
Matej 9 supports custom interaction types defined in Matej administration. Add support for any type of interaction.

Interaction will have two named constructors - `withItem()` and `withAliasedItem()`, both will accept interaction type as a string in first argument.

- `Interaction:withItem('interaction-type', 'user-id', 'item-id')`
- `Interaction:withAliasedItem('interaction-type', 'user-id', 'item-id-alias', 'item-id')`

Both will also accept timestamp as last optional argument. Remove all other arguments that are no longer supported by Matej.

```php
$response = $matej->request()
    ->events()
    ->addInteraction(\Lmc\Matej\Model\Command\Interaction:withItem('purchase', 'user123',  'item123'))
    ->addUserMerge(...)
    ...
    ->send();
```

Interaction attributes will be added using methods `setAttribute(string $key, mixed $value)` and `setAttributes(array $attributes)`.

- Class `Lmc\Matej\Model\Command\Constants\InteractionType` will be removed. It will be replaced by string variable.
- Methods for creating specific interaction type from `Lmc\Matej\Model\Command\Constants\InteractionType` eg. `detailView`, `purchase` will be removed. They'll be replaced by calling constructor directly.
- There will be no required arguments for Matej. Validation of passed arguments will be done server-side. Client will only validate that argument interactionType and argument keys are sensible strings (strings without whitespaces). Value has to be serializable to int, double, string or bool. Argument value validations `typeIdentifier()`, `between()`, `greaterThan()` will be removed.

**Comment by VincTheSecond** [comment]
Just to be exact -- custom interactions and their attributes will be configurable by us, not by our clients by themselves in the Matej Admin.
