### ISSUE TITLE
Update documentation and write a migration roadmap for users  

### ISSUE THREAD

**Issue by VincTheSecond** [lmc-eu/matej-client-php#110]

**Comment by JakubTesarek** [comment]
I assume this is the only documentation for the client we have: https://github.com/lmc-eu/matej-client-php/blob/master/README.md

**Comment by OndraM** [comment]
@JakubTesarek Is this issue fully covered by https://github.com/lmc-eu/matej-client-php/blob/master/UPGRADE-3.0.md ? Can we close this?

**Comment by JakubTesarek** [comment]
Yes, new features are fully covered by documentation.
