### ISSUE TITLE
Unify self vs static usage

### ISSUE THREAD

**Issue by ghost** [lmc-eu/matej-client-php#17]
Some classes use `new self()` while others use `new static()`. Perhaps it would be a good idea to use `static` everywhere so factory methods work as expected should inheritance get involved.

The same goes for `self::` versus `static::`. Why not use `static::` so static members can be overridden?

Also consider using `@return static` instead of `@return self` so code-completion works in these cases. For example - phpStorm complains about line 14 even though the call would succeed:

![image](https://user-images.githubusercontent.com/33895432/33125534-25dda018-cf81-11e7-9864-ad20b6a99ee9.png)

**Comment by OndraM** [comment]
@Fantomas-7 interested in making this happen? Maybe as part of this sprint?

**Comment by ghost** [comment]
@OndraM Sure. I'll send a PR this week, this should not take long.
