### ISSUE TITLE
Transpiled PHP 5.6 code does not contain proper type annotations

### ISSUE THREAD

**Issue by jirinovak** [lmc-eu/matej-client-php#33]
E.g.

```
$matej = new Matej('client-id', 'api-key');
$matej->request()->setupItemProperties() // returns mixed
```

so IDE is not able to autocomplete.

**Comment by OndraM** [comment]
My idea was to use some tool which finds PHP7 return typehints, and converts them to PHPDoc - this will be part of the transpilation process for PHP 5.6. However I was unable to find one :-(. (Only opposite direction :-D https://github.com/dunglas/phpdoc-to-typehint). Maybe you can have a look?

In the meanwhile, I manually backported the typehints to the RequestBuilderFactory - see https://github.com/lmc-eu/matej-client-php/pull/34 . It may help with this use - I hope in other cases PHPStorm is able to guess the return type (or is there any other issue, @jirinovak ?).

However I consider this more as a temporary workaround, and I'd like to find some more automatic solution, which will not require to add the redundant phpdocs to the PHP7 code...

**Comment by jirinovak** [comment]
Thanks for #34.

Right now I do not know about another problem.

**Comment by OndraM** [comment]
Ok, closing this for now. We may reopen this later, however...
