### ISSUE TITLE
Support for more combinations of user ids in recommendation request

### ISSUE THREAD

**Issue by kubasimon** [lmc-eu/matej-client-php#63]
Current implementation of recommendation endpoint is checking user ids for (interaction, merge, recommendation)
``` 
     (A,  null,  A)
     (A, A -> ?, ?)
     (?, ? -> A, A)
```

After implementing RAD-1015, client should also allow:

```
   (B, A -> B, B)
```

**Comment by OndraM** [comment]
:+1: Sure, the client will follow the API behavior. Do you know any ETA about the implementation in Matej (RAD-1015)?

**Comment by OndraM** [comment]
This is being rolled now to the API. 

@tenerd Do you need to use the feature now? We may implement it, but it may take a while until we get to it. If you'd like to contribute, it may be sooner - I'll try to do CR ASAP if you will send a PR. I believe the change should not be that big even with tests.
