### ISSUE TITLE
Make Recommendations response return list of objects by default

### ISSUE THREAD

**Issue by foglcz** [lmc-eu/matej-client-php#81]
As a developer, I'd like to have new RecommendationResponse format as default behaviour.

When sending an `UserRecommendationRequest`, we're omitting `parameters` argument (due to it's default being `null`.) This is correct at this time.

For the future, we'd like to change this default to `['item_id']` so that Matej returns a list of objects in recommendation responses - and deprecate returning list of item ids on Matejs side.

**Comment by OndraM** [comment]
Resolved by #82
